#set the name, addr and environment type for the server
name: appblueprint.client
env: "dev"

#set up the folders
folders:
  assets: ../assets
  models: ../app
  views: ../views

#set up the template folder and settings
templates:
  dir: ../templates
  ext: .tmpl
